import gradio as gr
import whisper
from gtts import gTTS
import os
import uuid
import tempfile
import requests


# Load the Whisper model (small or base for performance)
whisper_model = whisper.load_model("base")

# Set your Groq API key
GROQ_API_KEY = "upload_your_api_key"
GROQ_MODEL = "llama-3.1-8b-instant"  # Example model, check Groq docs for latest

# Function to transcribe audio
def transcribe_audio(audio_path):
    result = whisper_model.transcribe(audio_path)
    return result["text"]

# Function to call Groq's LLaMA model
def generate_response(prompt):
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.7
    }

    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 200:
        return response.json()["choices"][0]["message"]["content"]
    else:
        return "Error: Failed to get response from Groq API."

# Function to convert text to voice using gTTS
def text_to_speech(text):
    tts = gTTS(text)
    temp_audio = os.path.join(tempfile.gettempdir(), f"{uuid.uuid4()}.mp3")
    tts.save(temp_audio)
    return temp_audio

# Main chatbot pipeline
def chatbot_pipeline(audio):
    # Step 1: Transcribe voice input
    transcribed_text = transcribe_audio(audio)

    # Step 2: Generate response using LLaMA model via Groq API
    response_text = generate_response(transcribed_text)

    # Step 3: Convert response to speech
    response_audio = text_to_speech(response_text)

    return transcribed_text, response_text, response_audio

# Gradio Interface
interface = gr.Interface(
    fn=chatbot_pipeline,
    inputs=gr.Audio(type="filepath", label="🎙️ Speak now"),
    outputs=[
        gr.Textbox(label="📝 Transcribed Text"),
        gr.Textbox(label="🤖 AI Response"),
        gr.Audio(label="🔊 Response Audio")
    ],
    title="🎤 Voice to Voice Chatbot Application",
    description="Speak into your mic or upload audio file and get responses generated by LLaMA model, with both voice and text output!"
)

# Launch the interface
interface.launch()
